title: JohnnyBlocks's Steam Deck Blog

author:
  name: JohnnyBlocks

description: >
    Welcome to JohnnyBlocks's Steam Deck Blog and Collection of Resources and How To's to let you LEVEL-UP your Steam Deck. 

show_excerpts: true 
excerpt_separator: <!--more-->

permalink: date

minima:
   date_format: "%Y-%m-%d"
   skin:   dark
   
   social_links:
    - { platform: steam,    
        title:    "Steam: JohnnyBlocks",
        user_url: "https://steamcommunity.com/id/JohnnyBlocks"}
    - { platform: github,     
        title:    "GitHub: JohnnyBlocks",
        user_url: "https://github.com/JohnnyBlocks"} 
    - { platform: instagram,
        title:    "Instagram: @JohnnyBlocks",
        user_url: "https://www.instagram.com/JohnnyBlocks"}
    - { platform: telegram,
        title:    "Telegram: @JohnnyBlocks",
        user_url: "https://t.me/JohnnyBlocks"}
    - { platform: youtube,
        title:    "YouTube: @JohnnyBlocks",
        user_url: "https://www.youtube.com/@JohnnyBlocks"}

header_pages:
 - about.md

theme: minima


plugins:
 - jekyll-feed
 - jekyll-seo-tag