remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Johnny's Steam Deck Guide
description: Collection of Resources and How To Do's to let you LEVEL-UP your Steam Deck
show_downloads: false
