remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-them

title: [SteamDeck How-To Guide]
description: [Collection of Guides to Level Up the Deck]
show_downloads: [true]
google_analytics: [G-TF1K7SFX8T]