title: JohnnyBlocks's Steam Deck Cookbook
author:
  name: JohnnyBlocks
description: >
    JohnnyBlocks's Collection of Resources and How To's to let you LEVEL-UP your Steam Deck. 
show_excerpts: false 

minima:
   date_format: "%Y-%m-%d %H:%M"
   skin:   dark
   
   social_links:
    - { platform: steam,    
        title:    "Steam: JohnnyBlocks",
        user_url: "https://steamcommunity.com/id/JohnnyBlocks"}
    - { platform: github,     
        title:    "GitHub: JohnnyBlocks",
        user_url: "https://github.com/JohnnyBlocks"} 
    - { platform: instagram,
        title:    "Instagram: @JohnnyBlocks",
        user_url: "https://www.instagram.com/JohnnyBlocks"}
    - { platform: telegram,
        title:    "Telegram: @JohnnyBlocks",
        user_url: "https://t.me/JohnnyBlocks"}
    - { platform: youtube,
        title:    "YouTube: @JohnnyBlocks",
        user_url: "https://www.youtube.com/@JohnnyBlocks"}

header_pages:
 - about.md

theme: minima


plugins:
 - jekyll-feed
 - jekyll-seo-tag